name: build
on:
  push:
    branches: main
  pull_request:
    branches: main
jobs:
  dotnet-build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
        
    - name: Build
      run: dotnet build "./StudentGradeManager.sln" -c Release